-- The current version of every resource. pid is the surrogate key everything
-- else joins on; fhir_id is the logical id a client chooses and sees.
--
-- Separating the two is deliberate. Clients supply arbitrary strings as ids on
-- PUT, and those ids are what appear in references, but joins want a compact
-- integer. Conflating them makes every index table carry a variable-length key.
CREATE TABLE resource (
  pid           BIGINT  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  resource_type TEXT    NOT NULL,
  fhir_id       TEXT    NOT NULL,
  version_id    BIGINT  NOT NULL,
  last_updated  BIGINT  NOT NULL,          -- microseconds since the epoch
  deleted       BOOLEAN NOT NULL DEFAULT FALSE,
  content       BYTEA,                     -- NULL for a tombstone
  UNIQUE (resource_type, fhir_id)
);
CREATE INDEX idx_resource_type ON resource (resource_type, last_updated DESC, pid DESC);

-- Every version ever written, including tombstones. A delete is a version, not
-- an erasure: history has to show that the resource existed and stopped.
CREATE TABLE resource_history (
  resource_type TEXT    NOT NULL,
  fhir_id       TEXT    NOT NULL,
  version_id    BIGINT  NOT NULL,
  last_updated  BIGINT  NOT NULL,
  deleted       BOOLEAN NOT NULL DEFAULT FALSE,
  content       BYTEA,
  PRIMARY KEY (resource_type, fhir_id, version_id)
);
CREATE INDEX idx_history_updated      ON resource_history (last_updated DESC);
CREATE INDEX idx_history_type_updated ON resource_history (resource_type, last_updated DESC);

-- Search indexes, one table per parameter type.
--
-- The same tables and the same B-tree indexes as the SQLite schema, in this
-- engine's spelling. Nothing here is PostgreSQL-specific: no JSONB, no
-- expression indexes, nothing that would make the two schemas diverge in
-- meaning rather than in syntax. "seq" carries which occurrence of a composite
-- parameter's base expression a row came from, and is zero for every ordinary
-- parameter.

CREATE TABLE idx_string (
  pid   BIGINT NOT NULL REFERENCES resource (pid) ON DELETE CASCADE,
  code  TEXT   NOT NULL,
  seq   INTEGER NOT NULL DEFAULT 0,
  norm  TEXT   NOT NULL,   -- case- and accent-folded, for matching
  exact TEXT   NOT NULL    -- as written, for the :exact modifier
);
CREATE INDEX idx_string_lookup ON idx_string (code, norm);
CREATE INDEX idx_string_pid    ON idx_string (pid);

CREATE TABLE idx_token (
  pid    BIGINT NOT NULL REFERENCES resource (pid) ON DELETE CASCADE,
  code   TEXT   NOT NULL,
  seq    INTEGER NOT NULL DEFAULT 0,
  system TEXT   NOT NULL,
  value  TEXT   NOT NULL
);
CREATE INDEX idx_token_lookup ON idx_token (code, value, system);
CREATE INDEX idx_token_pid    ON idx_token (pid);

CREATE TABLE idx_reference (
  pid         BIGINT NOT NULL REFERENCES resource (pid) ON DELETE CASCADE,
  code        TEXT   NOT NULL,
  seq         INTEGER NOT NULL DEFAULT 0,
  target_type TEXT   NOT NULL,
  target_id   TEXT   NOT NULL,
  url         TEXT   NOT NULL
);
CREATE INDEX idx_reference_lookup ON idx_reference (code, target_type, target_id);
CREATE INDEX idx_reference_pid    ON idx_reference (pid);

-- Dates are stored as the interval they denote, because "2024" is a year rather
-- than an instant. Prefix comparisons are interval algebra over these bounds.
CREATE TABLE idx_date (
  pid  BIGINT NOT NULL REFERENCES resource (pid) ON DELETE CASCADE,
  code TEXT   NOT NULL,
  seq  INTEGER NOT NULL DEFAULT 0,
  low  BIGINT NOT NULL,
  high BIGINT NOT NULL
);
CREATE INDEX idx_date_lookup ON idx_date (code, low, high);
CREATE INDEX idx_date_pid    ON idx_date (pid);

CREATE TABLE idx_quantity (
  pid    BIGINT NOT NULL REFERENCES resource (pid) ON DELETE CASCADE,
  code   TEXT   NOT NULL,
  seq    INTEGER NOT NULL DEFAULT 0,
  low    DOUBLE PRECISION NOT NULL,
  high   DOUBLE PRECISION NOT NULL,
  system TEXT   NOT NULL,
  unit   TEXT   NOT NULL
);
CREATE INDEX idx_quantity_lookup ON idx_quantity (code, low, high);
CREATE INDEX idx_quantity_pid    ON idx_quantity (pid);

CREATE TABLE idx_uri (
  pid   BIGINT NOT NULL REFERENCES resource (pid) ON DELETE CASCADE,
  code  TEXT   NOT NULL,
  seq   INTEGER NOT NULL DEFAULT 0,
  value TEXT   NOT NULL
);
CREATE INDEX idx_uri_lookup ON idx_uri (code, value);
CREATE INDEX idx_uri_pid    ON idx_uri (pid);

CREATE TABLE idx_number (
  pid  BIGINT NOT NULL REFERENCES resource (pid) ON DELETE CASCADE,
  code TEXT   NOT NULL,
  seq  INTEGER NOT NULL DEFAULT 0,
  low  DOUBLE PRECISION NOT NULL,
  high DOUBLE PRECISION NOT NULL
);
CREATE INDEX idx_number_lookup ON idx_number (code, low, high);
CREATE INDEX idx_number_pid    ON idx_number (pid);

-- Full-text index backing _text and _content.
--
-- This is the one genuinely engine-specific part of the schema: FTS5 on SQLite,
-- tsvector with a GIN index here. Everything above is ordinary tables both
-- engines index identically, so this table is the whole of the divergence
-- rather than the start of it.
--
-- The 'simple' configuration is chosen for parity: it folds case and splits on
-- word boundaries without stemming, which is what FTS5's default tokenizer
-- does. An English stemmer would make the same query match different documents
-- on the two engines, which is exactly the kind of drift a shared test suite
-- exists to prevent.
CREATE TABLE idx_fulltext (
  pid       BIGINT PRIMARY KEY REFERENCES resource (pid) ON DELETE CASCADE,
  narrative TSVECTOR,   -- the rendered narrative, markup stripped: what _text searches
  content   TSVECTOR    -- every text value in the resource: what _content searches
);
CREATE INDEX idx_fulltext_narrative ON idx_fulltext USING GIN (narrative);
CREATE INDEX idx_fulltext_content   ON idx_fulltext USING GIN (content);
